# Sequences can use just H/P monomers or all 20 amino acids (automatically converted to H/P).
sequence: MGLSDGEWQLVLNVWGKVEADVAGHGQEVLIRSHVWGECPVLPALLSGVRALSESHQKRLRKDSRDDDGDDGDGDNDNDDGDGDDDDGDDDGDNDNDDDDGDGDDDGDGDDDRDDSDGGGGDHADDDNGNDDGDDDGHPETLEKFDKFKHLKTADEMKASEDLKKHGNTVLTALGGILKKKGHHEAELKPLAQSHATKHKIPVKYLEFISDAIIHVLQSKHPGDFGADAQAAMNKALELFRNDMAAKYKELGFQG

# This is an optional initial structure
structure:
  use_structure: false
  coordinates: [ [ 0,0 ], [ 0,1 ], ... ]  # only needed if use_structure: true

# Simulation configuration
simulation:
  folding_steps: 5000  # Number of folding steps
  annealing: true  # Whether to apply annealing or not
  temperature: 5.0  # Initial annealing temperature

# Plot configuration
plot:
  create_gif: true  # Whether to create a gif for representing evolution or not

# Seed for reproducibility (None for random)
seed: 42