sequence: MGLSDGEWQLVLNVWGKVEADVAGHGQEVLIRSHVWGECPVLPALLSGVRALSESHQKRLRKDSRDDDGDDGDGDNDNDDGDGDDDDGDDDGDNDNDDDDGDGDDDGDGDDDRDDSDGGGGDHADDDNGNDDGDDDGHPETLEKFDKFKHLKTADEMKASEDLKKHGNTVLTALGGILKKKGHHEAELKPLAQSHATKHKIPVKYLEFISDAIIHVLQSKHPGDFGADAQAAMNKALELFRNDMAAKYKELGFQG

structure:
  # The following is not compatible with the sequence above, so if use_structure is set to true it will not work.
  # Change the sequence/structure is you want to include the structure in the input.
  coordinates: [ [ 0,0 ],[ 0,1 ],[ 1,1 ],[ 1,2 ],[ 1,3 ],[ 2,3 ],[ 2,2 ],[ 2,1 ],[ 2,0 ],[ 2,-1 ],[ 1,-1 ],[ 0,-1 ],[ -1,-1 ],[ -1,-2 ],[ -1,-3 ],[ -1,-4 ],[ -1,-5 ],[ -1,-6 ],[ -1,-7 ],[ -1,-8 ],[ -2,-8 ],[ -3,-8 ],[ -3,-8 ],[ -4,-8 ],[ -5,-8 ],[ -5,-7 ],[ -5,-6 ],[ -5,-4 ],[ -5,-3 ],[ -6,-3 ] ]
  use_structure: false

simulation:
  folding_steps: 5000
  annealing: true
  temperature: 5.0

plot:
  create_gif: true

seed: 42